import { z } from "zod";

export const MetaSchema = z.object({
  request_id: z.string(),
  event_time: z.string(),
  arrival_time: z.string(),
  source: z.enum(["mock", "simulation", "replay", "paper", "live"]),
  quality_score: z.number(),
  trust_score: z.number(),
  replay_snapshot_id: z.string().nullable(),
  capability_status: z.enum(["reserved", "mock", "beta", "production"]),
});

export const ErrorEnvelopeSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string(),
    request_id: z.string(),
    retryable: z.boolean(),
    mode: z.enum(["MOCK", "SIMULATION", "REPLAY", "PAPER", "LIVE"]),
  }),
});

export const envelope = <T extends z.ZodTypeAny>(data: T) =>
  z.object({
    meta: MetaSchema,
    data,
  });

export const TimeSchema = z.object({
  time_mode: z.enum(["realtime", "virtual", "paused", "stepped"]),
  virtual_timestamp_ns: z.number(),
  wall_clock_time: z.string(),
  drift_ms: z.number(),
  source: z.enum(["mock", "system", "ntp", "ptp", "exchange_sync"]),
  sequence_number: z.number(),
});

export const ModeSchema = z.object({
  mode: z.enum(["MOCK", "SIMULATION", "REPLAY", "PAPER", "LIVE"]),
  display_label: z.string(),
  immutable: z.boolean(),
  allows_live_orders: z.boolean(),
  allows_broker_credentials: z.boolean(),
  watermark_text: z.string(),
});

export const KillSwitchSchema = z.object({
  state: z.enum(["armed", "triggered", "reset_pending"]),
  reason: z.string().nullable(),
  source: z.enum(["user_ui", "risk_engine", "circuit_breaker", "heartbeat_timeout", "system"]).nullable(),
  actor_id: z.string().nullable(),
  triggered_at: z.string().nullable(),
  blocks_order_paths: z.boolean(),
});

export const CapabilitySchema = z.object({
  name: z.string(),
  status: z.enum(["reserved", "mock", "beta", "production"]),
  ui_module: z.string(),
  backend_services: z.array(z.string()),
  required_data_contracts: z.array(z.string()),
  mock_replacement_strategy: z.string(),
  required_for_startup: z.boolean(),
  promotion_gates: z.array(z.string()),
});

export const CapabilitiesSchema = z.object({ capabilities: z.array(CapabilitySchema) });
export const WorkspaceLayoutSchema = z.object({
  version: z.number(),
  workspace_id: z.string(),
  active_workspace: z.string(),
  panels: z.array(z.object({
    id: z.string(),
    panel_type: z.string(),
    module: z.string(),
    bounds: z.object({
      x: z.number(),
      y: z.number(),
      w: z.number(),
      h: z.number(),
    }),
    state: z.record(z.unknown()),
    capability_requirement: z.string(),
  })),
  global_settings: z.record(z.unknown()),
  updated_at: z.string(),
});
export const PipelineSchema = z.object({
  mode: z.string(),
  steps: z.array(z.object({ name: z.string(), status: z.string(), latency_ms: z.number(), message: z.string() })),
  fast_path_enabled: z.boolean(),
  live_order_routing_enabled: z.boolean(),
});
export const DecisionSchema = z.object({
  final_action: z.string(),
  confidence: z.number(),
  votes: z.array(z.object({ engine: z.string(), vote: z.string(), confidence: z.number(), reason: z.string() })),
  narrative: z.object({ text: z.string(), read_only: z.boolean(), cannot_execute_orders: z.boolean(), cannot_override_risk: z.boolean() }),
  audit: z.array(z.object({ timestamp: z.string(), narrative_id: z.string(), model_version: z.string(), confidence_score: z.number(), explanation_chain: z.array(z.string()), human_reviewed: z.boolean(), reviewer_id: z.string().nullable() })),
});
export const PortfolioSchema = z.object({
  gross_exposure_pct: z.number(),
  sector_concentration_pct: z.number(),
  correlation_cluster_risk: z.string(),
  drawdown_governor: z.string(),
  live_positions_enabled: z.boolean(),
});
export const RiskSchema = z.object({
  hypothetical_exposure: z.number(),
  max_drawdown_simulated: z.number(),
  var95: z.number(),
  concentration_risk: z.record(z.number()),
  kill_switch_distance: z.number(),
  disclaimer: z.string(),
});
export const MarketDNASchema = z.object({
  price_score: z.number(),
  volatility_score: z.number(),
  options_score: z.number(),
  breadth_score: z.number(),
  event_score: z.number(),
  flow_score: z.number(),
  calibrated_breakout_probability: z.number(),
  calibrated_failure_probability: z.number(),
  status: z.string(),
});
export const MicrostructureSchema = z.object({
  order_book_imbalance: z.number(),
  sweep_events: z.number(),
  absorption_events: z.number(),
  spoofing_warnings: z.number(),
  hidden_liquidity_suspicion: z.number(),
  imbalance_propagation_score: z.number(),
  status: z.string(),
});
export const CandleBarSchema = z.object({
  symbol: z.string(),
  timeframe: z.string(),
  timestamp_ns: z.number(),
  open: z.number(),
  high: z.number(),
  low: z.number(),
  close: z.number(),
  volume: z.number().nullable(),
  source: z.string(),
  sequence_number: z.number(),
});
export const CandleSeriesSchema = z.object({
  symbol: z.string(),
  timeframe: z.string(),
  bars: z.array(CandleBarSchema),
  snapshot_id: z.string().nullable(),
  schema_version: z.string(),
});

export const BehaviorDataQualityIssueSchema = z.object({
  code: z.string(),
  severity: z.enum(["info", "warning", "blocker"]),
  message: z.string(),
  sequence_number: z.number().nullable(),
  timestamp_ns: z.number().nullable(),
});

export const BehaviorDataQualityResultSchema = z.object({
  symbol: z.string(),
  timeframe: z.string(),
  checked_at: z.string(),
  total_bars: z.number(),
  valid_bars: z.number(),
  data_quality_score: z.number(),
  missing_volume_count: z.number(),
  invalid_ohlc_count: z.number(),
  duplicate_timestamp_count: z.number(),
  non_monotonic_count: z.number(),
  gap_count: z.number(),
  abnormal_print_count: z.number(),
  split_suspect_count: z.number(),
  volume_matching_enabled: z.boolean(),
  blocks_trade: z.boolean(),
  issues: z.array(BehaviorDataQualityIssueSchema),
});

export const PointInTimeGuardSchema = z.object({
  symbol: z.string(),
  source_timeframe: z.string(),
  decision_time_ns: z.number(),
  execution_time_ns: z.number().nullable(),
  timeframe_duration_ns: z.number(),
  allowed_bars: z.number(),
  blocked_bars: z.number(),
  future_bar_blocked: z.number(),
  incomplete_candle_blocked: z.number(),
  latest_allowed_timestamp_ns: z.number().nullable(),
  passed: z.boolean(),
  blocks_trade: z.boolean(),
  reasons: z.array(z.string()),
});

export const BehaviorOhlcvImportSchema = z.object({
  import_version: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  row_count: z.number(),
  parsed_bar_count: z.number(),
  persisted_snapshot_id: z.string().nullable(),
  payload_hash: z.string(),
  series: CandleSeriesSchema,
  quality: BehaviorDataQualityResultSchema,
  point_in_time: PointInTimeGuardSchema,
  warnings: z.array(z.string()),
  safe_for_research: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  runtime_dependency_on_legacy_stock_app: z.boolean(),
});
export const ReplaySchema = z.object({
  session_id: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  state: z.string(),
  current_timestamp_ns: z.number(),
  events: z.array(z.object({
    event_id: z.string(),
    parent_event_id: z.string().nullable(),
    virtual_timestamp_ns: z.number(),
    source_mode: z.string(),
    sequence_number: z.number(),
    symbol: z.string(),
    payload: z.record(z.unknown()),
    watermark: z.string().nullable(),
  })),
});
export const ReplayArchiveSchema = z.array(z.object({
  session_id: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  state: z.string(),
  created_at: z.string(),
  event_count: z.number(),
}));
export const ExecutionSchema = z.object({
  slippage_pct: z.number(),
  queue_position_estimate: z.number(),
  partial_fill_probability: z.number(),
  adverse_selection_risk: z.string(),
  simulation_only: z.boolean(),
});
export const OrderPathStatusSchema = z.object({
  live_order_routing_enabled: z.boolean(),
  simulation_only: z.boolean(),
  broker_credentials_configured: z.boolean(),
  kill_switch_state: z.enum(["armed", "triggered", "reset_pending"]),
  accepts_simulated_orders: z.boolean(),
  blocks_reason: z.string().nullable(),
  required_gates: z.array(z.string()),
});
export const DataQualitySchema = z.object({
  lookback_years: z.number(),
  survivorship_bias: z.boolean(),
  look_ahead_leakage: z.boolean(),
  sample_size: z.number(),
  notes: z.array(z.string()),
});
export const PointInTimeSnapshotSchema = z.object({
  snapshot_id: z.string(),
  symbol: z.string(),
  source_mode: z.string(),
  seed: z.number(),
  as_of_timestamp_ns: z.number(),
  created_at: z.string(),
  schema_version: z.string(),
  payload_hash: z.string(),
  payload: z.record(z.unknown()),
  immutable: z.boolean(),
});
export const FeatureVersionSchema = z.object({
  feature_hash: z.string(),
  name: z.string(),
  schema_version: z.string(),
  pipeline_version: z.string(),
  source_commit: z.string(),
  created_at: z.string(),
  input_snapshot_id: z.string(),
  parameters: z.record(z.unknown()),
});
export const MockIngestResultSchema = z.object({
  snapshot: PointInTimeSnapshotSchema,
  feature_versions: z.array(FeatureVersionSchema),
});
export const SnapshotListSchema = z.array(PointInTimeSnapshotSchema);
export const FeatureRegistrySchema = z.array(FeatureVersionSchema);
export const IntegritySchema = z.object({
  data_source: z.string(),
  generation_timestamp: z.string(),
  model_version: z.string().nullable(),
  calibration_date: z.string().nullable(),
  assumptions: z.array(z.string()),
  confidence_interval: z.tuple([z.number(), z.number()]).nullable(),
  disclaimer: z.string(),
});
export const AuditSchema = z.array(z.object({
  event_id: z.string(),
  timestamp: z.string(),
  level: z.string(),
  message: z.string(),
  source: z.string(),
  mode: z.string(),
}));
export const AuditIntegritySchema = z.object({
  event_count: z.number(),
  hashed_event_count: z.number(),
  chain_valid: z.boolean(),
  head_hash: z.string().nullable(),
  first_event_time: z.string().nullable(),
  last_event_time: z.string().nullable(),
  algorithm: z.literal("sha256-canonical-json"),
  checked_at: z.string(),
  issues: z.array(z.string()),
});
export const KnowledgeGraphSchema = z.object({
  schema_version: z.string(),
  generated_at: z.string(),
  root: z.string(),
  summary: z.record(z.unknown()),
  nodes: z.array(z.record(z.unknown())),
  edges: z.array(z.record(z.unknown())),
});
export const StorageStatusSchema = z.object({
  status: z.enum(["ready", "error"]),
  db_path: z.string(),
  audit_events: z.number(),
  replay_sessions: z.number(),
  replay_events: z.number(),
  capability_snapshots: z.number(),
  point_in_time_snapshots: z.number(),
  feature_versions: z.number(),
  workspace_layouts: z.number(),
  request_logs: z.number(),
  behavior_analysis_results: z.number(),
  behavior_memory_records: z.number(),
  behavior_benchmark_runs: z.number(),
  behavior_safety_reports: z.number(),
  memory_quarantines: z.number(),
  golden_replay_fixtures: z.number(),
  behavior_benchmark_reports: z.number(),
  release_checklists: z.number(),
  release_approvals: z.number(),
  release_evidence_bundles: z.number(),
  release_evidence_artifacts: z.number(),
  behavior_scenario_coverage_reports: z.number(),
  executor_transport_outbox: z.number(),
});

export const ObservabilityStatusSchema = z.object({
  status: z.literal("ready"),
  log_format: z.literal("json"),
  request_count: z.number(),
  error_count: z.number(),
  p95_latency_ms: z.number(),
  required_fields: z.array(z.string()),
  recent_events: z.array(z.object({
    request_id: z.string(),
    run_id: z.string(),
    decision_id: z.string().nullable(),
    timestamp: z.string(),
    method: z.string(),
    path: z.string(),
    status_code: z.number(),
    latency_ms: z.number(),
    actor_id: z.string(),
    role: z.string(),
    mode: z.enum(["MOCK", "SIMULATION", "REPLAY", "PAPER", "LIVE"]),
    error_code: z.string().nullable(),
  })),
});

export const BehaviorSpecSchema = z.object({
  purpose: z.string(),
  no_blind_prediction_rule: z.string(),
  universal_agreement_rule: z.string(),
  low_evidence_message: z.string(),
  narrative_explanation_only_invariant: z.string(),
  layer_contracts: z.array(z.object({
    layer_index: z.number(),
    layer_name: z.string(),
    contract_name: z.string(),
    status: z.enum(["reserved", "mock", "beta", "production"]),
    required: z.boolean(),
  })),
  output_columns: z.array(z.object({
    index: z.number(),
    name: z.string(),
    group: z.string(),
  })),
  verbatim_registry: z.array(z.record(z.unknown())),
  live_trading_blocked: z.boolean(),
  stock_app_source_root: z.string(),
});

export const BehaviorOutputColumnsSchema = z.array(z.object({
  index: z.number(),
  name: z.string(),
  group: z.string(),
}));

export const BehaviorAnalysisSchema = z.object({
  symbol: z.string(),
  timeframe: z.string(),
  run_id: z.string(),
  result: z.record(z.unknown()),
  columns: z.array(z.string()),
  safety_gates: z.array(z.string()),
  reason_tree: z.record(z.string()),
  live_trade_route_attempted: z.boolean(),
});

export const BehaviorContextSchema = z.object({
  context_version: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  direction: z.string(),
  levels: z.object({
    context_version: z.string(),
    symbol: z.string(),
    timeframe: z.string(),
    latest_close: z.number().nullable(),
    calculated_vwap: z.number().nullable(),
    price_vs_vwap_pct: z.number().nullable(),
    vwap_state: z.string(),
    opening_range_high: z.number().nullable(),
    opening_range_low: z.number().nullable(),
    opening_range_state: z.string(),
    cpr_pivot: z.number().nullable(),
    cpr_bc: z.number().nullable(),
    cpr_tc: z.number().nullable(),
    cpr_state: z.string(),
    pdh_state: z.string(),
    pdl_state: z.string(),
    vpd_state: z.string(),
    support_resistance_flags: z.array(z.string()),
    level_respect_score: z.number(),
    blocks_trade: z.boolean(),
    reasons: z.array(z.string()),
  }),
  htf: z.object({
    context_version: z.string(),
    symbol: z.string(),
    decision_time_ns: z.number(),
    direction: z.string(),
    records: z.array(z.object({
      timeframe: z.string(),
      usable_bars: z.number(),
      latest_close: z.number().nullable(),
      first_close: z.number().nullable(),
      slope_pct: z.number().nullable(),
      bias: z.string(),
      confirmed: z.boolean(),
      reason: z.string(),
    })),
    confirmed: z.boolean(),
    blocks_trade: z.boolean(),
    confidence_adjustment: z.number(),
    reasons: z.array(z.string()),
  }).nullable(),
  gap: z.object({
    context_version: z.string(),
    symbol: z.string(),
    timeframe: z.string(),
    opening_price: z.number().nullable(),
    latest_close: z.number().nullable(),
    previous_close: z.number(),
    gap_pct: z.number().nullable(),
    gap_type: z.string(),
    gap_fill_probability_pct: z.number(),
    gap_trap_risk: z.number(),
    blocks_trade: z.boolean(),
    reasons: z.array(z.string()),
  }).nullable(),
  market: z.object({
    context_version: z.string(),
    symbol: z.string(),
    direction: z.string(),
    index_direction: z.string(),
    sector_strength: z.string(),
    relative_strength_score: z.number(),
    market_alignment: z.string(),
    blocks_trade: z.boolean(),
    reasons: z.array(z.string()),
  }),
  final_context_bias: z.string(),
  context_quality_score: z.number(),
  blocks_trade: z.boolean(),
  reason_tree: z.record(z.string()),
});

export const SessionSegmentSchema = z.object({
  session_phase: z.string(),
  window_start: z.string(),
  window_end: z.string(),
  bar_count: z.number(),
  return_pct: z.number(),
  range_pct: z.number(),
  avg_volume: z.number().nullable(),
  volume_curve: z.string(),
  trend_bias: z.string(),
  continuation_score: z.number(),
  fakeout_risk: z.number(),
  trade_quality_score: z.number(),
  notes: z.array(z.string()),
});

export const SessionRhythmSchema = z.object({
  rhythm_version: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  trading_date: z.string().nullable(),
  day_of_week: z.string(),
  current_session_phase: z.string(),
  segments: z.array(SessionSegmentSchema),
  usual_open_behavior: z.string(),
  usual_midday_behavior: z.string(),
  usual_closing_behavior: z.string(),
  best_trade_window: z.string(),
  worst_trade_window: z.string(),
  fakeout_window: z.string(),
  continuation_window: z.string(),
  session_personality_score: z.number(),
  blocks_trade: z.boolean(),
  no_trade_reason: z.string().nullable(),
  reasons: z.array(z.string()),
});

export const SessionMemoryProfileSchema = z.object({
  symbol: z.string(),
  profile_version: z.string(),
  updated_at: z.string(),
  session_phase: z.string(),
  sample_count: z.number(),
  continuation_rate_pct: z.number(),
  fakeout_rate_pct: z.number(),
  average_move_atr: z.number(),
  usual_behavior: z.string(),
  best_trade_window: z.string(),
  worst_trade_window: z.string(),
  evidence_quality: z.enum(["LOW", "MEDIUM", "STRONG"]),
  minimum_sample_pass: z.boolean(),
  notes: z.array(z.string()),
});

export const DayOfWeekMemorySchema = z.object({
  memory_version: z.string(),
  symbol: z.string(),
  records: z.array(z.object({
    day_of_week: z.string(),
    sample_count: z.number(),
    continuation_rate_pct: z.number(),
    reversal_rate_pct: z.number(),
    fakeout_rate_pct: z.number(),
    average_next_move_atr: z.number(),
    best_session_phase: z.string(),
    worst_session_phase: z.string(),
    behavior_note: z.string(),
    minimum_sample_pass: z.boolean(),
  })),
  dominant_day_note: z.string(),
  minimum_sample_size: z.number(),
  total_samples: z.number(),
  blocks_strong_probability: z.boolean(),
  reasons: z.array(z.string()),
});

export const StockDnaSummarySchema = z.object({
  symbol: z.string(),
  profile_version: z.string(),
  updated_at: z.string(),
  session_rhythm: SessionRhythmSchema,
  session_memory: z.array(SessionMemoryProfileSchema),
  day_of_week_memory: DayOfWeekMemorySchema,
  stock_dna: z.object({
    symbol: z.string(),
    profile_version: z.string(),
    updated_at: z.string(),
    source: z.string(),
    usual_open_behavior: z.string(),
    usual_midday_behavior: z.string(),
    usual_closing_behavior: z.string(),
    best_trade_window: z.string(),
    worst_trade_window: z.string(),
    fakeout_window: z.string(),
    continuation_window: z.string(),
    level_respect_summary: z.record(z.unknown()),
    notes: z.array(z.string()),
  }),
  stock_personality_summary: z.string(),
  behavior_edges: z.array(z.string()),
  risk_warnings: z.array(z.string()),
  minimum_evidence_pass: z.boolean(),
  learning_status: z.enum(["mock_seeded", "learning", "calibrated", "quarantined"]),
});

export const DayShapeVectorSchema = z.object({
  gap_pct: z.number(),
  first_15m_return: z.number(),
  first_30m_range: z.number(),
  vwap_position_score: z.number(),
  trend_slope: z.number(),
  pullback_depth: z.number(),
  volume_curve: z.number(),
  atr_expansion: z.number(),
  high_break_time: z.string(),
  low_break_time: z.string(),
  close_position: z.number(),
  rejection_count: z.number(),
  breakout_failure_count: z.number(),
  vector_values: z.array(z.number()),
});

export const SimilarDayMatchSchema = z.object({
  match_id: z.string(),
  symbol: z.string(),
  similar_day_id: z.string(),
  similarity_score_pct: z.number(),
  outcome_label: z.string(),
  average_next_move_atr: z.number(),
  failure_reason: z.string().nullable(),
  replay_available: z.boolean(),
  pattern_id: z.string(),
  market_state: z.string(),
  session_phase: z.string(),
  similarity_method: z.string(),
  cosine_similarity_pct: z.number(),
  dtw_similarity_pct: z.number(),
  time_decay_weight: z.number(),
  evidence_quality: z.enum(["LOW", "MEDIUM", "STRONG"]),
  minimum_sample_pass: z.boolean(),
  feature_match_summary: z.string(),
  current_day_shape_vector: DayShapeVectorSchema.nullable(),
  matched_day_shape_vector: DayShapeVectorSchema.nullable(),
  no_trade_reason: z.string().nullable(),
});

export const PatternMemorySchema = z.object({
  memory_version: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  day_shape_vector: DayShapeVectorSchema,
  vector_fields: z.array(z.string()),
  similarity_methods: z.array(z.string()),
  matches: z.array(SimilarDayMatchSchema),
  historical_match_count: z.number(),
  minimum_sample_size: z.number(),
  minimum_sample_pass: z.boolean(),
  evidence_quality: z.enum(["LOW", "MEDIUM", "STRONG"]),
  continuation_probability_pct: z.number(),
  reversal_probability_pct: z.number(),
  fakeout_probability_pct: z.number(),
  range_probability_pct: z.number(),
  average_next_move_atr: z.number(),
  best_invalidation: z.string(),
  similar_day_ids: z.array(z.string()),
  replay_ready: z.boolean(),
  no_trade_reason: z.string().nullable(),
  reason_tree: z.record(z.string()),
});

export const SimilarDayReplaySchema = z.object({
  replay_version: z.string(),
  symbol: z.string(),
  similar_day_id: z.string(),
  match: SimilarDayMatchSchema,
  day_shape_vector: DayShapeVectorSchema.nullable(),
  events: z.array(z.object({
    event_id: z.string(),
    parent_event_id: z.string().nullable(),
    virtual_timestamp_ns: z.number(),
    source_mode: z.string(),
    sequence_number: z.number(),
    symbol: z.string(),
    payload: z.record(z.unknown()),
    watermark: z.string().nullable(),
  })),
  deterministic: z.boolean(),
  replay_notes: z.array(z.string()),
});

export const OutcomeLabelSchema = z.object({
  outcome_version: z.string(),
  run_id: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  direction: z.enum(["long", "short"]),
  pattern_id: z.string(),
  outcome_label: z.enum([
    "TARGET_HIT",
    "SL_HIT",
    "PARTIAL_WIN",
    "BREAKEVEN",
    "TIME_EXIT",
    "FAKE_BREAKOUT",
    "RETEST_SUCCESS",
    "RETEST_FAIL",
    "CHOP_NO_FOLLOWTHROUGH",
  ]),
  bars_to_target: z.number().nullable(),
  bars_to_sl: z.number().nullable(),
  max_profit_before_sl: z.number(),
  max_loss_before_target: z.number(),
  mfe: z.number(),
  mae: z.number(),
  target_hit_timestamp_ns: z.number().nullable(),
  sl_hit_timestamp_ns: z.number().nullable(),
  fakeout_detected: z.boolean(),
  reason: z.string(),
  audit_fields: z.record(z.unknown()),
});

export const FailurePatternSchema = z.object({
  failure_id: z.string(),
  symbol: z.string(),
  pattern_id: z.string(),
  outcome_label: OutcomeLabelSchema.shape.outcome_label,
  failure_reason: z.string(),
  contributing_factors: z.array(z.string()),
  severity: z.enum(["low", "medium", "high"]),
  created_at: z.string(),
});

export const FailureLibrarySchema = z.object({
  library_version: z.string(),
  symbol: z.string(),
  failures: z.array(FailurePatternSchema),
  most_common_failure: z.string().nullable(),
  no_trade_lessons: z.array(z.string()),
});

export const LearningTrustSchema = z.object({
  trust_version: z.string(),
  symbol: z.string(),
  records: z.array(z.object({
    trust_id: z.string(),
    symbol: z.string(),
    pattern_id: z.string(),
    sample_count: z.number(),
    predicted_probability_pct: z.number(),
    actual_success_rate_pct: z.number(),
    calibration_error_pct: z.number(),
    trust_score: z.number(),
    evidence_quality: z.enum(["LOW", "MEDIUM", "STRONG"]),
    notes: z.array(z.string()),
  })),
  aggregate_trust_score: z.number(),
  calibration_status: z.enum(["LOW_EVIDENCE", "CALIBRATING", "CALIBRATED", "QUARANTINED"]),
  minimum_sample_pass: z.boolean(),
  notes: z.array(z.string()),
});

export const RuntimeReadinessGateSchema = z.object({
  gate_id: z.string(),
  name: z.string(),
  status: z.string(),
  evidence: z.string(),
});

export const StockMemoryProfileSchema = z.object({
  memory_profile_version: z.string(),
  generated_at: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  snapshot_count: z.number(),
  memory_record_count: z.number(),
  historical_match_count: z.number(),
  minimum_sample_size: z.number(),
  minimum_sample_pass: z.boolean(),
  freshness_score: z.number(),
  stock_dna_summary: StockDnaSummarySchema,
  session_summary: z.record(z.unknown()),
  day_of_week_summary: z.record(z.unknown()),
  pattern_memory_summary: z.record(z.unknown()),
  similar_day_summary: z.record(z.unknown()),
  failure_summary: z.record(z.unknown()),
  trust_summary: z.record(z.unknown()),
  no_trade_memory_reasons: z.array(z.string()),
  output_hash: z.string(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  gates: z.array(RuntimeReadinessGateSchema),
  notes: z.array(z.string()),
});

export const KronosRuntimeStatusSchema = z.object({
  kronos_version: z.string(),
  service_status: z.string(),
  repo_path: z.string(),
  repo_present: z.boolean(),
  service_path: z.string(),
  service_present: z.boolean(),
  mode: z.string(),
  selected_model: z.string(),
  model_policy: z.record(z.string()),
  dependency_isolated: z.boolean(),
  api_imports_heavy_ml: z.boolean(),
  research_only: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const KronosServiceBridgeStatusSchema = z.object({
  bridge_version: z.string(),
  generated_at: z.string(),
  service_url: z.string().nullable(),
  service_configured: z.boolean(),
  service_present: z.boolean(),
  health_checked: z.boolean(),
  health_ok: z.boolean(),
  service_status: z.string(),
  timeout_ms: z.number(),
  fallback_to_mock: z.boolean(),
  fallback_reason: z.string(),
  dependency_isolated: z.boolean(),
  api_imports_heavy_ml: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const KronosInputValidationSchema = z.object({
  validation_version: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  candle_count: z.number(),
  decision_time_ns: z.number().nullable(),
  passed: z.boolean(),
  future_candle_rejected: z.boolean(),
  nan_or_inf_rejected: z.boolean(),
  invalid_ohlc_rejected: z.boolean(),
  incomplete_candle_rejected: z.boolean(),
  sequence_mismatch_rejected: z.boolean(),
  granularity_mismatch_rejected: z.boolean(),
  input_snapshot_hash: z.string(),
  blockers: z.array(z.string()),
  warnings: z.array(z.string()),
});

export const KronosForecastSchema = z.object({
  forecast_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  source_mode: z.string(),
  model_name: z.string(),
  model_version: z.string(),
  tokenizer_name: z.string(),
  input_validation: KronosInputValidationSchema,
  forecast_path: z.object({
    scenario_id: z.string(),
    path_type: z.string(),
    candles: z.array(z.record(z.union([z.number(), z.string()]))),
    expected_return_pct: z.number(),
    expected_move_atr: z.number(),
    trend_direction: z.string(),
    range_probability: z.number(),
    continuation_probability: z.number(),
    reversal_probability: z.number(),
  }),
  uncertainty: z.object({
    lower_path: z.array(z.number()),
    median_path: z.array(z.number()),
    upper_path: z.array(z.number()),
    uncertainty_score: z.number(),
    discarded_for_high_uncertainty: z.boolean(),
  }),
  expiry: z.object({
    generated_at: z.string(),
    valid_until: z.string(),
    horizon_bars: z.number(),
    expired: z.boolean(),
  }),
  sanity_check: z.object({
    passed: z.boolean(),
    max_allowed_move_pct: z.number(),
    max_observed_move_pct: z.number(),
    impossible_move_blocked: z.boolean(),
    reason: z.string(),
  }),
  forecast_confidence: z.number(),
  input_snapshot_id: z.string().nullable(),
  input_snapshot_hash: z.string(),
  output_hash: z.string(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  research_only: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  kronos_cannot_execute_orders: z.boolean(),
  kronos_cannot_override_no_trade: z.boolean(),
  kronos_cannot_override_risk: z.boolean(),
  notes: z.array(z.string()),
});

export const TwinEngineComparisonSchema = z.object({
  twin_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  symbol: z.string(),
  behavior_decision: z.string(),
  behavior_trade_allowed: z.boolean(),
  behavior_risk_blocked: z.boolean(),
  kronos_available: z.boolean(),
  kronos_direction: z.string(),
  kronos_confidence: z.number(),
  agreement_state: z.string(),
  arbiter_action: z.string(),
  agreement_score: z.number(),
  conflict_reasons: z.array(z.string()),
  evidence_hash: z.string(),
  twin_agreement_hash: z.string(),
  kronos: KronosForecastSchema.nullable(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  kronos_cannot_execute_orders: z.boolean(),
  kronos_cannot_override_no_trade: z.boolean(),
  kronos_cannot_override_risk: z.boolean(),
  notes: z.array(z.string()),
});

export const TwinMachineDashboardSchema = z.object({
  dashboard_version: z.string(),
  generated_at: z.string(),
  symbol: z.string(),
  comparison: TwinEngineComparisonSchema,
  conflicts: z.array(z.object({
    conflict_id: z.string(),
    symbol: z.string(),
    agreement_state: z.string(),
    behavior_decision: z.string(),
    kronos_direction: z.string(),
    conflict_reasons: z.array(z.string()),
    evidence_hash: z.string(),
    created_at: z.string(),
  })),
  reliability: z.object({
    reliability_version: z.string(),
    symbol: z.string(),
    sample_count: z.number(),
    behavior_only_accuracy: z.number(),
    kronos_only_accuracy: z.number(),
    twin_arbiter_accuracy: z.number(),
    fakeout_avoidance: z.number(),
    no_trade_quality: z.number(),
    calibration_error: z.number(),
    minimum_sample_pass: z.boolean(),
    notes: z.array(z.string()),
  }),
  tournament: z.object({
    tournament_version: z.string(),
    run_id: z.string(),
    symbol: z.string(),
    scenario_count: z.number(),
    deterministic: z.boolean(),
    behavior_score: z.number(),
    kronos_score: z.number(),
    twin_score: z.number(),
    leaderboard: z.array(z.record(z.union([z.string(), z.number()]))),
    promotion_allowed: z.boolean(),
    evidence_hash: z.string(),
    trade_allowed: z.boolean(),
    order_routing_enabled: z.boolean(),
    live_trading_blocked: z.boolean(),
    notes: z.array(z.string()),
  }),
  openalgo_intent_preview: z.object({
    intent_version: z.string(),
    intent_id: z.string(),
    symbol: z.string(),
    side: z.string(),
    twin_decision: z.string(),
    broker_order_created: z.boolean(),
    trade_allowed: z.boolean(),
    order_routing_enabled: z.boolean(),
    live_trading_blocked: z.boolean(),
    export_status: z.string(),
  }).passthrough(),
  forecast_path_points: z.array(z.record(z.union([z.string(), z.number()]))),
  forecast_fan: z.object({
    lower: z.array(z.number()),
    median: z.array(z.number()),
    upper: z.array(z.number()),
  }),
  ghost_path_summary: z.record(z.union([z.string(), z.number(), z.boolean()])),
  safety_gate_matrix: z.array(z.object({
    gate: z.string(),
    passed: z.boolean(),
    effect: z.string(),
  })),
  reliability_leaderboard: z.array(z.record(z.union([z.string(), z.number()]))),
  conflict_explorer: z.array(z.object({
    source: z.string(),
    state: z.string(),
    reason: z.string(),
  })),
  recommended_workspace_action: z.string(),
  dashboard_hash: z.string(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const BotHandoffVerificationSchema = z.object({
  verifier_version: z.string(),
  verified_at: z.string(),
  intent_id: z.string(),
  symbol: z.string(),
  target_executor: z.string(),
  accepted_for_external_review: z.boolean(),
  rejected: z.boolean(),
  rejection_reasons: z.array(z.string()),
  gate_results: z.array(z.object({
    gate: z.string(),
    passed: z.boolean(),
    evidence: z.string(),
  })),
  signature_valid: z.boolean(),
  duplicate_detected: z.boolean(),
  expired: z.boolean(),
  mode_permission: z.string(),
  kill_switch_rechecked: z.boolean(),
  human_veto_required: z.boolean(),
  external_human_approval_present: z.boolean(),
  external_risk_check_passed: z.boolean(),
  external_account_state_checked: z.boolean(),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  export_allowed: z.boolean(),
  verification_hash: z.string(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const ExecutorDryRunPackageSchema = z.object({
  package_version: z.string(),
  package_id: z.string(),
  created_at: z.string(),
  symbol: z.string(),
  target_executor: z.string(),
  requested_by: z.string(),
  intent: z.object({
    intent_id: z.string(),
    intent_signature: z.string(),
    duplicate_key: z.string(),
    side: z.string(),
    export_status: z.string(),
    broker_order_created: z.boolean(),
    order_routing_enabled: z.boolean(),
    live_trading_blocked: z.boolean(),
  }).passthrough(),
  verification: BotHandoffVerificationSchema,
  handoff_contract: z.record(z.unknown()),
  executor_required_checks: z.array(z.string()),
  rejection_examples: z.array(z.object({
    case_id: z.string(),
    title: z.string(),
    mutated_fields: z.record(z.unknown()),
    expected_rejection_reasons: z.array(z.string()),
    expected_executor_action: z.string(),
  })),
  artifact_dir: z.string(),
  package_file_path: z.string(),
  manifest_file_path: z.string(),
  package_sha256: z.string(),
  manifest_sha256: z.string(),
  package_size_bytes: z.number(),
  manifest_size_bytes: z.number(),
  package_hash: z.string(),
  dry_run_only: z.boolean(),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

const ExecutorGoldenFixtureSchema = z.object({
  fixture_version: z.string(),
  fixture_id: z.string(),
  scenario: z.enum(["accepted_for_review", "missing_external_checks", "duplicate_intent", "expired_intent"]),
  expected_accepted_for_external_review: z.boolean(),
  expected_rejected: z.boolean(),
  expected_rejection_reasons: z.array(z.string()),
  package: ExecutorDryRunPackageSchema,
  expected_package_sha256: z.string(),
  expected_manifest_sha256: z.string(),
  expected_package_hash: z.string(),
  deterministic: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const ExecutorGoldenFixtureRegistrySchema = z.object({
  registry_version: z.string(),
  generated_at: z.string(),
  fixture_count: z.number(),
  fixtures: z.array(ExecutorGoldenFixtureSchema),
  fixture_hashes: z.record(z.string()),
  registry_hash: z.string(),
  deterministic: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const ExecutorGoldenRegistryVerificationSchema = z.object({
  verification_version: z.string(),
  registry_version: z.string(),
  registry_hash: z.string(),
  fixture_count: z.number(),
  passed_count: z.number(),
  all_passed: z.boolean(),
  verifications: z.array(z.object({
    verification_version: z.string(),
    fixture_id: z.string(),
    package_verification: z.object({
      verification_version: z.string(),
      package_id: z.string(),
      verified_at: z.string(),
      package_file_exists: z.boolean(),
      manifest_file_exists: z.boolean(),
      package_sha256_matches: z.boolean(),
      manifest_sha256_matches: z.boolean(),
      package_json_parseable: z.boolean(),
      verified: z.boolean(),
      issues: z.array(z.string()),
      broker_order_created: z.boolean(),
      order_routing_enabled: z.boolean(),
      live_trading_blocked: z.boolean(),
    }),
    acceptance_matches: z.boolean(),
    rejection_reasons_match: z.boolean(),
    package_hash_matches: z.boolean(),
    safety_invariants_match: z.boolean(),
    passed: z.boolean(),
    issues: z.array(z.string()),
    broker_order_created: z.boolean(),
    order_routing_enabled: z.boolean(),
    live_trading_blocked: z.boolean(),
  })),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const ExecutorAdapterConformanceSchema = z.object({
  conformance_version: z.string(),
  evaluated_at: z.string(),
  adapter_name: z.string(),
  adapter_version: z.string(),
  registry_hash: z.string(),
  registry_hash_matches: z.boolean(),
  expected_fixture_count: z.number(),
  observed_fixture_count: z.number(),
  passed_count: z.number(),
  all_passed: z.boolean(),
  missing_fixture_ids: z.array(z.string()),
  unexpected_fixture_ids: z.array(z.string()),
  duplicate_fixture_ids: z.array(z.string()),
  cases: z.array(z.object({
    fixture_id: z.string(),
    expected_accepted_for_external_review: z.boolean(),
    observed_accepted_for_external_review: z.boolean(),
    expected_rejected: z.boolean(),
    observed_rejected: z.boolean(),
    expected_rejection_reasons: z.array(z.string()),
    observed_rejection_reasons: z.array(z.string()),
    outcome_matches: z.boolean(),
    rejection_reasons_match: z.boolean(),
    safety_invariants_match: z.boolean(),
    passed: z.boolean(),
    issues: z.array(z.string()),
  })),
  report_hash: z.string(),
  signature_algorithm: z.string(),
  promotion_allowed: z.boolean(),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const ExecutorTransportAcknowledgementSchema = z.object({
  acknowledgement_version: z.string(),
  delivery_id: z.string(),
  idempotency_key: z.string(),
  adapter_name: z.string(),
  adapter_version: z.string(),
  receipt_id: z.string(),
  received_at: z.string(),
  accepted_for_external_review: z.boolean(),
  duplicate: z.boolean(),
  package_hash: z.string(),
  broker_credentials_received: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const ExecutorTransportOutboxRecordSchema = z.object({
  transport_version: z.string(),
  delivery_id: z.string(),
  idempotency_key: z.string(),
  created_at: z.string(),
  updated_at: z.string(),
  adapter_url: z.string().nullable(),
  service_identity: z.string(),
  package: ExecutorDryRunPackageSchema,
  status: z.enum(["pending", "delivering", "acknowledged", "retry_wait", "manual_review", "cancelled", "dead_letter"]),
  attempt_count: z.number(),
  max_attempts: z.number(),
  next_attempt_at: z.string().nullable(),
  last_attempt_at: z.string().nullable(),
  last_error: z.string().nullable(),
  acknowledgement: ExecutorTransportAcknowledgementSchema.nullable(),
  automatic_execution_allowed: z.boolean(),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const ExecutorTransportStatusSchema = z.object({
  status_version: z.string(),
  generated_at: z.string(),
  adapter_url: z.string().nullable(),
  configured: z.boolean(),
  health_checked: z.boolean(),
  health_ok: z.boolean(),
  service_identity: z.string(),
  service_auth_configured: z.boolean(),
  timeout_ms: z.number(),
  circuit_state: z.enum(["closed", "open", "half_open"]),
  circuit_failure_count: z.number(),
  circuit_failure_threshold: z.number(),
  circuit_open_until: z.string().nullable(),
  pending_count: z.number(),
  retry_wait_count: z.number(),
  acknowledged_count: z.number(),
  manual_review_count: z.number(),
  cancelled_count: z.number(),
  dead_letter_count: z.number(),
  automatic_execution_allowed: z.boolean(),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const ExecutorTransportTraceSchema = z.object({
  trace_id: z.string(),
  delivery_id: z.string(),
  event_time: z.string(),
  event_type: z.enum([
    "enqueued",
    "delivery_started",
    "acknowledged",
    "retry_scheduled",
    "manual_review",
    "dead_lettered",
    "cancelled",
    "operator_retry",
    "recovered",
    "circuit_blocked",
  ]),
  status: z.string(),
  attempt_count: z.number(),
  latency_ms: z.number().nullable(),
  error_code: z.string().nullable(),
  actor_id: z.string(),
  details: z.record(z.unknown()),
  previous_trace_hash: z.string().nullable(),
  trace_hash: z.string(),
});

export const TransportResilienceSchema = z.object({
  resilience_version: z.string(),
  generated_at: z.string(),
  evidence_window: z.number(),
  health_samples: z.number(),
  delivery_attempts: z.number(),
  successful_deliveries: z.number(),
  failed_deliveries: z.number(),
  availability_pct: z.number(),
  p95_delivery_latency_ms: z.number(),
  retry_rate_pct: z.number(),
  backlog_count: z.number(),
  dead_letter_count: z.number(),
  objectives: z.array(z.object({
    objective_id: z.string(),
    name: z.string(),
    target: z.number(),
    observed: z.number(),
    unit: z.string(),
    status: z.enum(["pass", "warn", "fail", "low_evidence"]),
    sample_count: z.number(),
    minimum_sample_count: z.number(),
    blocks_promotion: z.boolean(),
    reason: z.string(),
  })),
  alerts: z.array(z.object({
    alert_id: z.string(),
    severity: z.enum(["info", "warning", "critical"]),
    code: z.string(),
    message: z.string(),
    active: z.boolean(),
    runbook: z.string(),
  })),
  incident: z.object({
    incident_id: z.string(),
    opened_at: z.string(),
    updated_at: z.string(),
    status: z.enum(["open", "acknowledged", "resolved"]),
    severity: z.enum(["warning", "critical"]),
    title: z.string(),
    alert_codes: z.array(z.string()),
    acknowledged_by: z.string().nullable(),
    acknowledged_at: z.string().nullable(),
    resolution_note: z.string().nullable(),
    broker_order_created: z.boolean(),
    order_routing_enabled: z.boolean(),
    live_trading_blocked: z.boolean(),
  }).nullable(),
  overall_status: z.enum(["healthy", "degraded", "critical", "low_evidence"]),
  promotion_allowed: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const TransportFaultHarnessSchema = z.object({
  harness_version: z.string(),
  generated_at: z.string(),
  sample_count: z.number(),
  deterministic: z.boolean(),
  passed_count: z.number(),
  scenario_count: z.number(),
  all_passed: z.boolean(),
  scenarios: z.array(z.object({
    scenario: z.enum(["healthy", "latency_breach", "availability_breach", "backlog_breach", "dead_letter", "circuit_open"]),
    expected_status: z.enum(["healthy", "degraded", "critical"]),
    observed_status: z.enum(["healthy", "degraded", "critical", "low_evidence"]),
    expected_alert_code: z.string().nullable(),
    observed_alert_codes: z.array(z.string()),
    passed: z.boolean(),
  })),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const TransportTraceIntegritySchema = z.object({
  verification_version: z.string(),
  verified_at: z.string(),
  delivery_id: z.string().nullable(),
  trace_count: z.number(),
  verified_count: z.number(),
  valid: z.boolean(),
  issues: z.array(z.string()),
  head_hash: z.string().nullable(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const TransportSecurityPostureSchema = z.object({
  security_version: z.string(),
  generated_at: z.string(),
  active_key_configured: z.boolean(),
  previous_key_configured: z.boolean(),
  adapter_allowlist: z.array(z.string()),
  nonce_replay_protection: z.boolean(),
  timestamp_skew_seconds: z.number(),
  max_request_bytes: z.number(),
  rate_limit_per_minute: z.number(),
  trace_integrity: TransportTraceIntegritySchema,
  checks: z.array(z.object({
    check_id: z.string(),
    name: z.string(),
    passed: z.boolean(),
    severity: z.enum(["info", "warning", "critical"]),
    evidence: z.string(),
  })),
  overall_status: z.enum(["pass", "warn", "fail"]),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const TransportSecurityThreatReportSchema = z.object({
  report_version: z.string(),
  generated_at: z.string(),
  passed_count: z.number(),
  threat_count: z.number(),
  all_passed: z.boolean(),
  results: z.array(z.object({
    threat: z.enum(["invalid_signature", "stale_timestamp", "replayed_nonce", "disallowed_host", "oversized_payload", "unsafe_ack", "trace_tamper"]),
    blocked: z.boolean(),
    expected_control: z.string(),
  })),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

const DeploymentReadinessCheckSchema = z.object({
  check_id: z.string(),
  name: z.string(),
  status: z.enum(["pass", "warn", "fail"]),
  evidence: z.string(),
  blocks_deployment: z.boolean(),
});

export const DeploymentReadinessSchema = z.object({
  readiness_version: z.string(),
  generated_at: z.string(),
  target: z.literal("research_mock_stack"),
  configuration: z.object({
    fingerprint_version: z.string(),
    generated_at: z.string(),
    fingerprint: z.string(),
    expected_fingerprint: z.string().nullable(),
    drift_detected: z.boolean(),
    non_secret_configuration: z.record(z.union([z.string(), z.number(), z.boolean(), z.null()])),
    secrets_included: z.boolean(),
  }),
  checks: z.array(DeploymentReadinessCheckSchema),
  pass_count: z.number(),
  warn_count: z.number(),
  fail_count: z.number(),
  ready: z.boolean(),
  live_broker_deployment_allowed: z.boolean(),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const DeploymentSmokeSchema = z.object({
  smoke_version: z.string(),
  generated_at: z.string(),
  checks: z.array(DeploymentReadinessCheckSchema),
  passed_count: z.number(),
  check_count: z.number(),
  all_passed: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

const StaticSafetyScanSchema = z.object({
  scan_version: z.string(),
  generated_at: z.string(),
  scanned_file_count: z.number(),
  scanned_roots: z.array(z.string()),
  forbidden_pattern_count: z.number(),
  findings: z.array(z.object({
    finding_id: z.string(),
    file_path: z.string(),
    line_number: z.number(),
    pattern_id: z.string(),
    excerpt: z.string(),
    severity: z.enum(["critical", "warning"]),
  })),
  passed: z.boolean(),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

const ReleaseCandidateManifestSchema = z.object({
  manifest_version: z.string(),
  release_id: z.string(),
  generated_at: z.string(),
  target: z.literal("research_mock_stack"),
  artifact_count: z.number(),
  artifacts: z.array(z.object({
    artifact_id: z.string(),
    relative_path: z.string(),
    sha256: z.string(),
    size_bytes: z.number(),
    required: z.boolean(),
    present: z.boolean(),
  })),
  manifest_sha256: z.string(),
  manifest_path: z.string().nullable(),
  immutable: z.boolean(),
  contains_secrets: z.boolean(),
  contains_broker_credentials: z.boolean(),
  contains_live_orders: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
});

export const FinalProductionReadinessAuditSchema = z.object({
  audit_version: z.string(),
  generated_at: z.string(),
  target: z.literal("research_mock_stack"),
  release_scope: z.string(),
  gates: z.array(z.object({
    gate_id: z.string(),
    name: z.string(),
    status: z.enum(["pass", "warn", "fail"]),
    evidence: z.string(),
    blocks_release: z.boolean(),
  })),
  pass_count: z.number(),
  warn_count: z.number(),
  fail_count: z.number(),
  research_stack_ready: z.boolean(),
  production_research_release_candidate: z.boolean(),
  live_trading_ready: z.boolean(),
  static_safety_scan: StaticSafetyScanSchema,
  release_manifest: ReleaseCandidateManifestSchema,
  deployment_readiness_version: z.string(),
  deployment_smoke_version: z.string(),
  transport_resilience_version: z.string(),
  transport_resilience_status: z.enum(["healthy", "low_evidence", "degraded", "critical"]),
  capability_count: z.number(),
  required_capability_count: z.number(),
  required_capabilities_covered: z.boolean(),
  operator_signoff_required: z.boolean(),
  operator_signoff_present: z.boolean(),
  broker_credentials_present: z.boolean(),
  broker_order_created: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const TradeDecisionSchema = z.object({
  decision_version: z.string(),
  symbol: z.string(),
  final_trade_decision: z.enum([
    "NO_TRADE",
    "BUY_BREAKOUT",
    "SELL_BREAKDOWN",
    "BUY_RETEST",
    "SELL_RETEST",
    "BUY_FADE",
    "SELL_FADE",
    "WATCH_ONLY",
    "AVOID_CHOP",
    "FAKEOUT_WARNING",
  ]),
  trade_allowed: z.boolean(),
  universal_agreement_pass: z.boolean(),
  confidence_pct: z.number(),
  agreement_checks: z.record(z.boolean()),
  gates: z.array(z.object({
    gate: z.string(),
    passed: z.boolean(),
    severity: z.enum(["info", "warning", "block"]),
    reason: z.string(),
  })),
  no_trade: z.object({
    symbol: z.string(),
    active: z.boolean(),
    no_trade_reason: z.string().nullable(),
    blocking_gates: z.array(z.string()),
    wait_for: z.array(z.string()),
  }),
  reason_tree: z.object({
    reason_version: z.string(),
    symbol: z.string(),
    nodes: z.record(z.string()),
    ordered_reasons: z.array(z.string()),
    read_only: z.boolean(),
    cannot_execute_orders: z.boolean(),
    cannot_override_calibrated_probabilities: z.boolean(),
  }),
  output_updates: z.record(z.unknown()),
  narrative_explanation: z.string(),
  live_trade_route_attempted: z.boolean(),
});

export const RiskSizingSchema = z.object({
  risk_version: z.string(),
  symbol: z.string(),
  decision: TradeDecisionSchema.shape.final_trade_decision,
  position_size: z.number(),
  risk_per_trade_pct: z.number(),
  capital_to_use: z.number(),
  max_loss_amount: z.number(),
  reward_amount: z.number(),
  risk_reward: z.number(),
  portfolio: z.object({
    sector: z.string(),
    index: z.string(),
    sector_exposure_pct: z.number(),
    index_exposure_pct: z.number(),
    correlation_risk: z.enum(["low", "medium", "high"]),
    portfolio_heat_pct: z.number(),
    blocks_trade: z.boolean(),
    reasons: z.array(z.string()),
  }),
  daily_loss: z.object({
    daily_pnl: z.number(),
    max_daily_loss_amount: z.number(),
    daily_loss_limit_hit: z.boolean(),
    cooldown_active: z.boolean(),
    cooldown_minutes: z.number(),
    reasons: z.array(z.string()),
  }),
  trade_allowed: z.boolean(),
  block_reasons: z.array(z.string()),
  sizing_formula: z.string(),
  no_live_route_attempted: z.boolean(),
});

export const ExecutionSimulationSchema = z.object({
  execution_version: z.string(),
  simulation_id: z.string(),
  symbol: z.string(),
  side: z.enum(["BUY", "SELL"]),
  order_type: z.enum(["MARKET", "LIMIT", "STOP"]),
  requested_quantity: z.number(),
  filled_quantity: z.number(),
  unfilled_quantity: z.number(),
  fill_status: z.enum(["FULL_FILL", "PARTIAL_FILL", "NO_FILL", "REJECTED_SIMULATION"]),
  fill_probability_pct: z.number(),
  fill_price: z.number().nullable(),
  reference_price: z.number(),
  fill_quality: z.enum(["excellent", "acceptable", "poor", "rejected", "no_fill"]),
  queue_position_estimate: z.number(),
  partial_fill_probability_pct: z.number(),
  no_fill_reason: z.string().nullable(),
  missed_trade_reason: z.string().nullable(),
  adverse_selection_risk: z.enum(["low", "medium", "high"]),
  costs: z.object({
    spread_cost_pct: z.number(),
    latency_slippage_pct: z.number(),
    market_impact_pct: z.number(),
    adverse_selection_cost_pct: z.number(),
    total_cost_pct: z.number(),
  }),
  market_impact_model: z.string(),
  latency_model: z.string(),
  deterministic: z.boolean(),
  simulation_only: z.boolean(),
  live_route_attempted: z.boolean(),
  safety_notes: z.array(z.string()),
});

export const BehaviorFrontendPanelMapSchema = z.object({
  map_version: z.string(),
  workspace: z.literal("behavior"),
  total_panels: z.number(),
  mock_panels: z.number(),
  reserved_panels: z.number(),
  panels: z.array(z.object({
    panel_id: z.string(),
    title: z.string(),
    workspace: z.literal("behavior"),
    layer_index: z.number().nullable(),
    layer_name: z.string(),
    contract_name: z.string(),
    endpoint: z.string(),
    output_fields: z.array(z.string()),
    fallback_state: z.enum(["loading", "mock", "reserved", "blocked", "offline"]),
    capability_name: z.string(),
    manifest_status: z.enum(["reserved", "mock", "beta", "production"]),
    required_for_mvp: z.boolean(),
  })),
  safety_invariants: z.array(z.string()),
});

export const BehaviorValidationSchema = z.object({
  validation_version: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  validation_type: z.enum(["walk_forward", "out_of_sample"]),
  folds: z.array(z.object({
    fold_index: z.number(),
    train_start_day: z.number(),
    train_end_day: z.number(),
    test_start_day: z.number(),
    test_end_day: z.number(),
    train_samples: z.number(),
    test_samples: z.number(),
    leakage_pass: z.boolean(),
    minimum_sample_pass: z.boolean(),
    win_rate_pct: z.number(),
    profit_factor: z.number(),
    expectancy_r: z.number(),
    max_drawdown_pct: z.number(),
    average_r: z.number(),
    median_r: z.number(),
    trade_count: z.number(),
    notes: z.array(z.string()),
  })),
  aggregate_win_rate_pct: z.number(),
  aggregate_profit_factor: z.number(),
  aggregate_expectancy_r: z.number(),
  aggregate_max_drawdown_pct: z.number(),
  total_trades: z.number(),
  no_future_leakage: z.boolean(),
  deterministic: z.boolean(),
  live_trading_blocked: z.boolean(),
  promotion_allowed: z.boolean(),
  promotion_blockers: z.array(z.string()),
  notes: z.array(z.string()),
});

export const BehaviorDriftSchema = z.object({
  safety_version: z.string(),
  symbol: z.string(),
  feature_name: z.string(),
  baseline_sample_count: z.number(),
  live_sample_count: z.number(),
  mean_shift_z: z.number(),
  volatility_shift_ratio: z.number(),
  population_stability_index: z.number(),
  drift_score: z.number(),
  drift_status: z.enum(["stable", "watch", "quarantine"]),
  memory_quarantine_required: z.boolean(),
  confidence_multiplier: z.number(),
  promotion_allowed: z.boolean(),
  promotion_blockers: z.array(z.string()),
  notes: z.array(z.string()),
});

export const BehaviorOODSchema = z.object({
  safety_version: z.string(),
  symbol: z.string(),
  ood_score: z.number(),
  max_feature_distance: z.number(),
  ood_status: z.enum(["normal", "watch", "block"]),
  confidence_blocked: z.boolean(),
  trade_blocked: z.boolean(),
  feature_results: z.array(z.object({
    feature_name: z.string(),
    current_value: z.number(),
    expected_min: z.number(),
    expected_max: z.number(),
    hard_min: z.number(),
    hard_max: z.number(),
    distance_score: z.number(),
    status: z.enum(["inside", "soft_outlier", "hard_outlier"]),
    reason: z.string(),
  })),
  promotion_allowed: z.boolean(),
  promotion_blockers: z.array(z.string()),
  notes: z.array(z.string()),
});

export const RealityGapSchema = z.object({
  safety_version: z.string(),
  symbol: z.string(),
  slippage_drift_pct: z.number(),
  fill_rate_drift_pct: z.number(),
  latency_drift_ms: z.number(),
  pnl_drift_r: z.number(),
  reality_gap_score: z.number(),
  alert: z.boolean(),
  severity: z.enum(["normal", "watch", "critical"]),
  promotion_allowed: z.boolean(),
  promotion_blockers: z.array(z.string()),
  notes: z.array(z.string()),
});

export const BehaviorAcpSchema = z.object({
  safety_version: z.string(),
  checks: z.array(z.object({
    check_id: z.string(),
    purpose: z.string(),
    status: z.enum(["pass", "fail"]),
    evidence: z.string(),
    blocks_promotion: z.boolean(),
  })),
  pass_count: z.number(),
  fail_count: z.number(),
  promotion_allowed: z.boolean(),
  promotion_blockers: z.array(z.string()),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const BehaviorSafetyReportSchema = z.object({
  report_version: z.string(),
  report_id: z.string(),
  symbol: z.string(),
  created_at: z.string(),
  drift: BehaviorDriftSchema,
  ood: BehaviorOODSchema,
  reality_gap: RealityGapSchema,
  acp: BehaviorAcpSchema,
  promotion_allowed: z.boolean(),
  memory_quarantine_required: z.boolean(),
  confidence_blocked: z.boolean(),
  reality_gap_alert: z.boolean(),
  report_hash: z.string(),
  immutable: z.boolean(),
  notes: z.array(z.string()),
});

export const MemoryQuarantineSchema = z.object({
  quarantine_version: z.string(),
  quarantine_id: z.string(),
  symbol: z.string(),
  created_at: z.string(),
  status: z.enum(["active", "released", "rebuild_pending"]),
  reason: z.string(),
  source_report_id: z.string().nullable(),
  actor_id: z.string(),
  affected_memory_ids: z.array(z.string()),
  confidence_blocked: z.boolean(),
  memory_promotion_blocked: z.boolean(),
  read_policy: z.enum(["read_allowed_for_audit_only", "read_allowed_low_confidence", "read_blocked"]),
  release_requires: z.array(z.string()),
  notes: z.array(z.string()),
});

export const MemoryRebuildPlanSchema = z.object({
  rebuild_version: z.string(),
  plan_id: z.string(),
  symbol: z.string(),
  quarantine_id: z.string().nullable(),
  created_at: z.string(),
  allowed_to_rebuild: z.boolean(),
  required_inputs: z.array(z.string()),
  rebuild_steps: z.array(z.string()),
  promotion_gates: z.array(z.string()),
  estimated_safe_status: z.enum(["blocked", "shadow_only", "mock_ready"]),
  notes: z.array(z.string()),
});

export const GoldenReplayFixtureSchema = z.object({
  fixture_version: z.string(),
  fixture_id: z.string(),
  symbol: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  expected_event_count: z.number(),
  expected_first_event_id: z.string(),
  expected_last_event_id: z.string(),
  expected_chain_hash: z.string(),
  safety_assertions: z.array(z.string()),
});

export const GoldenReplayVerificationSchema = z.object({
  verification_version: z.string(),
  fixture: GoldenReplayFixtureSchema,
  actual_event_count: z.number(),
  actual_first_event_id: z.string().nullable(),
  actual_last_event_id: z.string().nullable(),
  actual_chain_hash: z.string(),
  deterministic: z.boolean(),
  passed: z.boolean(),
  issues: z.array(z.string()),
  live_trading_blocked: z.boolean(),
});

export const BehaviorBenchmarkReportSchema = z.object({
  report_version: z.string(),
  report_id: z.string(),
  symbol: z.string(),
  created_at: z.string(),
  walk_forward: BehaviorValidationSchema,
  out_of_sample: BehaviorValidationSchema,
  safety_report: BehaviorSafetyReportSchema,
  golden_replay_verifications: z.array(GoldenReplayVerificationSchema),
  metrics: z.record(z.unknown()),
  promotion_allowed: z.boolean(),
  promotion_blockers: z.array(z.string()),
  report_hash: z.string(),
  immutable: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const ReleaseChecklistSchema = z.object({
  checklist_version: z.string(),
  checklist_id: z.string(),
  symbol: z.string(),
  target_mode: z.literal("REPLAY"),
  created_at: z.string(),
  benchmark_report_id: z.string(),
  gates: z.array(z.object({
    gate_id: z.string(),
    category: z.enum(["contracts", "data", "validation", "safety", "replay", "risk", "approval"]),
    description: z.string(),
    status: z.enum(["pass", "fail"]),
    evidence: z.string(),
    blocks_release: z.boolean(),
  })),
  pass_count: z.number(),
  fail_count: z.number(),
  technical_release_pass: z.boolean(),
  release_allowed: z.boolean(),
  release_blockers: z.array(z.string()),
  manual_approval_required: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const ReleaseApprovalSchema = z.object({
  approval_version: z.string(),
  approval_id: z.string(),
  symbol: z.string(),
  target_mode: z.literal("REPLAY"),
  approval_scope: z.literal("mock_to_replay"),
  benchmark_report_id: z.string(),
  checklist_id: z.string().nullable(),
  requested_by: z.string(),
  requested_at: z.string(),
  reason: z.string(),
  status: z.enum(["requested", "approved", "rejected", "expired"]),
  approved_by: z.string().nullable(),
  approved_at: z.string().nullable(),
  rejected_by: z.string().nullable(),
  rejected_at: z.string().nullable(),
  rejection_reason: z.string().nullable(),
  expires_at: z.string(),
  evidence: z.array(z.string()),
  live_trading_blocked: z.boolean(),
});

export const BenchmarkDrilldownSchema = z.object({
  drilldown_version: z.string(),
  report_id: z.string(),
  symbol: z.string(),
  generated_at: z.string(),
  metric_groups: z.record(z.record(z.unknown())),
  validation_summary: z.array(z.string()),
  safety_summary: z.array(z.string()),
  replay_summary: z.array(z.string()),
  promotion_summary: z.array(z.string()),
  live_trading_blocked: z.boolean(),
});

export const BehaviorScenarioCoverageItemSchema = z.object({
  item_version: z.string(),
  scenario_id: z.string(),
  scenario_family: z.enum(["opening_drive", "fakeout_reversal", "lunch_compression", "closing_drive", "gap_trap", "expiry_pin", "unknown"]),
  fixture_id: z.string(),
  seed: z.number(),
  expected_event_count: z.number(),
  actual_event_count: z.number(),
  deterministic: z.boolean(),
  passed: z.boolean(),
  chain_hash: z.string(),
  coverage_status: z.enum(["covered", "failed", "missing"]),
  safety_assertions: z.array(z.string()),
  issues: z.array(z.string()),
  notes: z.array(z.string()),
});

export const BehaviorScenarioCoverageReportSchema = z.object({
  coverage_version: z.string(),
  coverage_id: z.string(),
  symbol: z.string(),
  benchmark_report_id: z.string(),
  generated_at: z.string(),
  required_scenario_families: z.array(z.string()),
  covered_scenario_families: z.array(z.string()),
  missing_scenario_families: z.array(z.string()),
  total_scenarios: z.number(),
  passed_scenarios: z.number(),
  failed_scenarios: z.number(),
  deterministic_pass_rate_pct: z.number(),
  coverage_score_pct: z.number(),
  scenario_items: z.array(BehaviorScenarioCoverageItemSchema),
  promotion_allowed: z.boolean(),
  promotion_blockers: z.array(z.string()),
  immutable: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const RuntimeReadinessSchema = z.object({
  readiness_version: z.string(),
  generated_at: z.string(),
  project_root: z.string(),
  stock_app_source_root: z.string(),
  self_indicator_total: z.number(),
  self_indicator_returned: z.number(),
  pta_marker_total: z.number(),
  total_output_groups: z.number(),
  non_empty_sample_outputs: z.number(),
  empty_no_signal_outputs: z.number(),
  automated_indicator_tests_passed: z.number(),
  automated_indicator_tests_skipped: z.number(),
  chart_screens: z.record(z.boolean()),
  research_surfaces: z.record(z.boolean()),
  replay_surfaces: z.record(z.boolean()),
  indicator_groups: z.array(z.object({
    group_id: z.string(),
    source: z.enum(["self_indc", "pta_signal_markers"]),
    sample_status: z.enum(["non_empty_sample", "empty_no_signal_on_sample", "registered_marker"]),
    notes: z.string(),
  })),
  gates: z.array(z.object({
    gate_id: z.string(),
    name: z.string(),
    status: z.enum(["pass", "warn", "fail"]),
    evidence: z.string(),
    blocks_research: z.boolean(),
    remediation: z.string().nullable(),
  })),
  indicator_output_ready: z.boolean(),
  chart_output_ready: z.boolean(),
  research_activity_ready: z.boolean(),
  replay_ready: z.boolean(),
  safe_mode: z.boolean(),
  live_trading_blocked: z.boolean(),
  browser_recommended_ports: z.array(z.number()),
  notes: z.array(z.string()),
});

export const ReplayIndicatorValidationSchema = z.object({
  validation_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  symbol: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  event_count: z.number(),
  candle_count: z.number(),
  indicator_count: z.number(),
  chart_point_count: z.number(),
  replay_session_id: z.string(),
  candle_series: CandleSeriesSchema,
  indicator_points: z.array(z.object({
    sequence_number: z.number(),
    timestamp_ns: z.number(),
    close: z.number(),
    sma_3: z.number().nullable(),
    ema_5: z.number(),
    rsi_5: z.number(),
    vwap: z.number(),
    macd_fast_slow: z.number(),
    volume_z: z.number(),
    signal_flags: z.array(z.string()),
  })),
  chart_points: z.array(z.object({
    timestamp_ns: z.number(),
    open: z.number(),
    high: z.number(),
    low: z.number(),
    close: z.number(),
    volume: z.number(),
    indicator_overlay: z.record(z.number().nullable()),
    markers: z.array(z.string()),
  })),
  deterministic: z.boolean(),
  input_event_chain_hash: z.string(),
  output_hash: z.string(),
  no_future_leakage: z.boolean(),
  runtime_dependency_on_legacy_stock_app: z.boolean(),
  safe_mode: z.boolean(),
  live_trading_blocked: z.boolean(),
  gates: z.array(z.object({
    gate_id: z.string(),
    name: z.string(),
    status: z.enum(["pass", "warn", "fail"]),
    evidence: z.string(),
    blocks_research: z.boolean(),
    remediation: z.string().nullable(),
  })),
  notes: z.array(z.string()),
});

export const BehaviorChartReplaySchema = z.object({
  chart_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  base_validation_version: z.string(),
  symbol: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  timeframe: z.string(),
  event_count: z.number(),
  candle_count: z.number(),
  chart_point_count: z.number(),
  selected_sequence_number: z.number(),
  viewport: z.object({
    min_price: z.number(),
    max_price: z.number(),
    min_timestamp_ns: z.number(),
    max_timestamp_ns: z.number(),
    candle_count: z.number(),
    price_padding_pct: z.number(),
  }),
  chart_points: z.array(ReplayIndicatorValidationSchema.shape.chart_points.element),
  overlays: z.array(z.object({
    overlay_key: z.string(),
    label: z.string(),
    visible: z.boolean(),
    latest_value: z.number().nullable(),
    min_value: z.number().nullable(),
    max_value: z.number().nullable(),
    point_count: z.number(),
    purpose: z.string(),
  })),
  selected_candle: z.object({
    sequence_number: z.number(),
    timestamp_ns: z.number(),
    candle_direction: z.enum(["bullish", "bearish", "neutral"]),
    body_pct: z.number(),
    upper_wick_pct: z.number(),
    lower_wick_pct: z.number(),
    close_location_value: z.number(),
    marker_tags: z.array(z.string()),
    overlay_values: z.record(z.number().nullable()),
    evidence_rows: z.array(z.string()),
    reason: z.string(),
  }),
  input_event_chain_hash: z.string(),
  base_output_hash: z.string(),
  output_hash: z.string(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  runtime_dependency_on_legacy_stock_app: z.boolean(),
  safe_mode: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  gates: ReplayIndicatorValidationSchema.shape.gates,
  notes: z.array(z.string()),
});

export const BehaviorIndicatorExpansionSchema = z.object({
  expansion_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  base_matrix_version: z.string(),
  symbol: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  timeframe: z.string(),
  event_count: z.number(),
  candidate_output_groups: z.number(),
  base_indicator_count: z.number(),
  matrix_indicator_count: z.number(),
  promoted_indicator_count: z.number(),
  proxy_indicator_count: z.number(),
  blocked_indicator_count: z.number(),
  family_coverage: z.record(z.number()),
  items: z.array(z.object({
    row_id: z.string(),
    family: z.string(),
    layer_index: z.number().nullable(),
    contract_name: z.string(),
    status: z.enum(["promoted", "proxy", "blocked"]),
    signal: z.enum(["bullish", "bearish", "neutral", "watch", "blocked"]),
    latest_value: z.union([z.number(), z.string(), z.boolean()]).nullable(),
    normalized_score: z.number(),
    chart_overlay_key: z.string().nullable(),
    output_fields: z.record(z.union([z.number(), z.string(), z.boolean()]).nullable()),
    point_in_time_safe: z.boolean(),
    explanation: z.string(),
  })),
  input_event_chain_hash: z.string(),
  matrix_output_hash: z.string(),
  output_hash: z.string(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  runtime_dependency_on_legacy_stock_app: z.boolean(),
  safe_mode: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  gates: ReplayIndicatorValidationSchema.shape.gates,
  notes: z.array(z.string()),
});

export const ReplayIndicatorMatrixSchema = z.object({
  matrix_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  base_validation_version: z.string(),
  symbol: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  event_count: z.number(),
  timeframe: z.string(),
  base_indicator_count: z.number(),
  matrix_indicator_count: z.number(),
  chart_point_count: z.number(),
  ready_rows: z.number(),
  proxy_rows: z.number(),
  blocked_rows: z.number(),
  rows: z.array(z.object({
    row_id: z.string(),
    family: z.string(),
    layer_index: z.number().nullable(),
    contract_name: z.string(),
    source: z.enum(["replay_candle", "derived_overlay", "behavior_proxy", "safety_proxy"]),
    latest_value: z.union([z.number(), z.string(), z.boolean()]).nullable(),
    normalized_score: z.number(),
    signal: z.enum(["bullish", "bearish", "neutral", "watch", "blocked"]),
    chart_overlay_key: z.string().nullable(),
    required_inputs: z.array(z.string()),
    output_fields: z.record(z.union([z.number(), z.string(), z.boolean()]).nullable()),
    point_in_time_safe: z.boolean(),
    readiness_status: z.enum(["ready", "proxy", "blocked"]),
    explanation: z.string(),
  })),
  base_output_hash: z.string(),
  input_event_chain_hash: z.string(),
  output_hash: z.string(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  runtime_dependency_on_legacy_stock_app: z.boolean(),
  safe_mode: z.boolean(),
  live_trading_blocked: z.boolean(),
  gates: z.array(z.object({
    gate_id: z.string(),
    name: z.string(),
    status: z.enum(["pass", "warn", "fail"]),
    evidence: z.string(),
    blocks_research: z.boolean(),
    remediation: z.string().nullable(),
  })),
  notes: z.array(z.string()),
});

export const MatrixDecisionReadinessSchema = z.object({
  readiness_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  base_matrix_version: z.string(),
  symbol: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  event_count: z.number(),
  timeframe: z.string(),
  matrix_indicator_count: z.number(),
  ready_rows: z.number(),
  proxy_rows: z.number(),
  blocked_rows: z.number(),
  bullish_rows: z.number(),
  bearish_rows: z.number(),
  watch_rows: z.number(),
  neutral_rows: z.number(),
  directional_bias: z.enum(["LONG", "SHORT", "NEUTRAL"]),
  readiness_action: z.enum(["REPLAY_BUY_CANDIDATE", "REPLAY_SELL_CANDIDATE", "WAIT", "NO_TRADE", "BLOCK"]),
  simulated_decision_allowed: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  confidence_score: z.number(),
  agreement_score: z.number(),
  safety_score: z.number(),
  risk_score: z.number(),
  blocker_reasons: z.array(z.string()),
  gate_summary: z.record(z.number()),
  used_row_ids: z.array(z.string()),
  matrix_output_hash: z.string(),
  input_event_chain_hash: z.string(),
  output_hash: z.string(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  narrative_read_only: z.boolean(),
  live_trading_blocked: z.boolean(),
  gates: z.array(z.object({
    gate_id: z.string(),
    name: z.string(),
    status: z.enum(["pass", "warn", "fail"]),
    score: z.number(),
    threshold: z.number(),
    evidence: z.string(),
    blocks_decision: z.boolean(),
    remediation: z.string().nullable(),
  })),
  reason: z.string(),
  notes: z.array(z.string()),
});

export const TradeLifecycleSimulationSchema = z.object({
  lifecycle_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  symbol: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  event_count: z.number(),
  timeframe: z.string(),
  base_readiness_version: z.string(),
  base_chart_version: z.string(),
  readiness_action: MatrixDecisionReadinessSchema.shape.readiness_action,
  lifecycle_status: z.enum(["BLOCKED_BY_READINESS", "SHADOW_SIMULATED", "SHADOW_NO_FILL", "SHADOW_REJECTED"]),
  directional_bias: MatrixDecisionReadinessSchema.shape.directional_bias,
  entry_type: z.literal("NEXT_5M_OPEN_SHADOW"),
  entry_sequence_number: z.number(),
  entry_timestamp_ns: z.number(),
  entry_price: z.number(),
  stop_loss: z.number(),
  target: z.number(),
  risk_reward: z.number(),
  atr_proxy: z.number(),
  trade_state_path: z.array(z.string()),
  readiness: MatrixDecisionReadinessSchema,
  execution: ExecutionSimulationSchema,
  outcome: OutcomeLabelSchema,
  expected_MFE: z.number(),
  expected_MAE: z.number(),
  bars_to_target: z.number().nullable(),
  bars_to_sl: z.number().nullable(),
  blocker_reasons: z.array(z.string()),
  lifecycle_gate_summary: z.record(z.number()),
  gates: MatrixDecisionReadinessSchema.shape.gates,
  input_event_chain_hash: z.string(),
  readiness_output_hash: z.string(),
  outcome_run_id: z.string(),
  execution_simulation_id: z.string(),
  output_hash: z.string(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  simulation_only: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  narrative_read_only: z.boolean(),
  reason: z.string(),
  notes: z.array(z.string()),
});

export const TradeLifecycleScenarioComparisonItemSchema = z.object({
  label: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  readiness_action: MatrixDecisionReadinessSchema.shape.readiness_action,
  lifecycle_status: TradeLifecycleSimulationSchema.shape.lifecycle_status,
  directional_bias: MatrixDecisionReadinessSchema.shape.directional_bias,
  outcome_label: OutcomeLabelSchema.shape.outcome_label,
  fill_status: ExecutionSimulationSchema.shape.fill_status,
  fill_quality: ExecutionSimulationSchema.shape.fill_quality,
  entry_price: z.number(),
  stop_loss: z.number(),
  target: z.number(),
  risk_reward: z.number(),
  expected_MFE: z.number(),
  expected_MAE: z.number(),
  bars_to_target: z.number().nullable(),
  bars_to_sl: z.number().nullable(),
  blocker_count: z.number(),
  trade_state_path: z.array(z.string()),
  output_hash: z.string(),
  trade_allowed: z.boolean(),
  live_trading_blocked: z.boolean(),
  no_future_leakage: z.boolean(),
});

export const TradeLifecycleScenarioComparisonSchema = z.object({
  comparison_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  event_count: z.number(),
  scenario_count: z.number(),
  candidate_count: z.number(),
  blocked_count: z.number(),
  no_fill_count: z.number(),
  rejected_count: z.number(),
  target_hit_count: z.number(),
  stop_hit_count: z.number(),
  average_MFE: z.number(),
  average_MAE: z.number(),
  best_scenario_label: z.string().nullable(),
  worst_scenario_label: z.string().nullable(),
  items: z.array(TradeLifecycleScenarioComparisonItemSchema),
  all_trade_allowed_false: z.boolean(),
  all_order_routing_disabled: z.boolean(),
  all_live_trading_blocked: z.boolean(),
  all_simulation_only: z.boolean(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  output_hash: z.string(),
  gates: MatrixDecisionReadinessSchema.shape.gates,
  notes: z.array(z.string()),
});

export const LifecycleEvidenceRowContributionSchema = z.object({
  row_id: z.string(),
  family: z.string(),
  layer_index: z.number().nullable(),
  contract_name: z.string(),
  source: z.enum(["replay_candle", "derived_overlay", "behavior_proxy", "safety_proxy"]),
  signal: z.enum(["bullish", "bearish", "neutral", "watch", "blocked"]),
  readiness_status: z.enum(["ready", "proxy", "blocked"]),
  normalized_score: z.number(),
  contribution_kind: z.enum(["directional_positive", "directional_negative", "safety_pressure"]),
  contribution_score: z.number(),
  latest_value: z.union([z.number(), z.string(), z.boolean()]).nullable(),
  output_fields: z.record(z.union([z.number(), z.string(), z.boolean()]).nullable()),
  explanation: z.string(),
});

export const LifecycleEvidenceScenarioDrilldownSchema = z.object({
  label: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  readiness_action: MatrixDecisionReadinessSchema.shape.readiness_action,
  lifecycle_status: TradeLifecycleSimulationSchema.shape.lifecycle_status,
  directional_bias: MatrixDecisionReadinessSchema.shape.directional_bias,
  outcome_label: OutcomeLabelSchema.shape.outcome_label,
  fill_status: ExecutionSimulationSchema.shape.fill_status,
  fill_quality: ExecutionSimulationSchema.shape.fill_quality,
  agreement_score: z.number(),
  safety_score: z.number(),
  risk_score: z.number(),
  top_directional_drivers: z.array(LifecycleEvidenceRowContributionSchema),
  top_counter_drivers: z.array(LifecycleEvidenceRowContributionSchema),
  top_safety_pressures: z.array(LifecycleEvidenceRowContributionSchema),
  blocker_reasons: z.array(z.string()),
  reason: z.string(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  no_future_leakage: z.boolean(),
  output_hash: z.string(),
});

export const LifecycleEvidenceDrilldownSchema = z.object({
  evidence_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  event_count: z.number(),
  scenario_count: z.number(),
  candidate_count: z.number(),
  blocked_count: z.number(),
  base_comparison_version: z.string(),
  comparison_output_hash: z.string(),
  dominant_directional_driver: z.string().nullable(),
  dominant_safety_pressure: z.string().nullable(),
  items: z.array(LifecycleEvidenceScenarioDrilldownSchema),
  all_trade_allowed_false: z.boolean(),
  all_order_routing_disabled: z.boolean(),
  all_live_trading_blocked: z.boolean(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  narrative_read_only: z.boolean(),
  output_hash: z.string(),
  gates: MatrixDecisionReadinessSchema.shape.gates,
  notes: z.array(z.string()),
});

export const TradeabilityImprovementStepSchema = z.object({
  step_id: z.string(),
  category: z.enum([
    "directional_confirmation",
    "safety_pressure",
    "execution_quality",
    "risk_control",
    "evidence_quality",
    "permission_lock",
  ]),
  source_row_id: z.string().nullable(),
  priority: z.enum(["critical", "high", "medium", "low"]),
  current_value: z.number().nullable(),
  target_value: z.number().nullable(),
  action: z.string(),
  rationale: z.string(),
  blocks_promotion: z.boolean(),
});

export const ScenarioTradeabilityGuidanceSchema = z.object({
  label: z.string(),
  scenario_id: z.string(),
  seed: z.number(),
  readiness_action: MatrixDecisionReadinessSchema.shape.readiness_action,
  lifecycle_status: TradeLifecycleSimulationSchema.shape.lifecycle_status,
  directional_bias: MatrixDecisionReadinessSchema.shape.directional_bias,
  tradeability_status: z.enum(["BLOCKED", "AVOID", "RESEARCH_WATCH", "REPLAY_CANDIDATE_RESEARCH_ONLY"]),
  next_safe_action: z.enum([
    "NO_TRADE",
    "WAIT_FOR_RETEST",
    "IMPROVE_LIQUIDITY",
    "REPLAY_REVIEW_ONLY",
    "AVOID_FAKEOUT",
    "COLLECT_MORE_EVIDENCE",
  ]),
  tradeability_score: z.number(),
  best_driver_row_id: z.string().nullable(),
  worst_safety_row_id: z.string().nullable(),
  agreement_score: z.number(),
  safety_score: z.number(),
  risk_score: z.number(),
  promotion_blockers: z.array(z.string()),
  improvement_steps: z.array(TradeabilityImprovementStepSchema),
  reason: z.string(),
  must_remain_simulation_only: z.boolean(),
  trade_allowed: z.boolean(),
  order_routing_enabled: z.boolean(),
  live_trading_blocked: z.boolean(),
  no_future_leakage: z.boolean(),
  output_hash: z.string(),
});

export const TradeabilityGuidanceSchema = z.object({
  guidance_version: z.string(),
  generated_at: z.string(),
  run_id: z.string(),
  symbol: z.string(),
  timeframe: z.string(),
  event_count: z.number(),
  scenario_count: z.number(),
  blocked_count: z.number(),
  avoid_count: z.number(),
  research_watch_count: z.number(),
  replay_candidate_research_only_count: z.number(),
  base_evidence_version: z.string(),
  evidence_output_hash: z.string(),
  safest_scenario_label: z.string().nullable(),
  riskiest_scenario_label: z.string().nullable(),
  top_global_blocker: z.string().nullable(),
  items: z.array(ScenarioTradeabilityGuidanceSchema),
  all_trade_allowed_false: z.boolean(),
  all_order_routing_disabled: z.boolean(),
  all_live_trading_blocked: z.boolean(),
  deterministic: z.boolean(),
  no_future_leakage: z.boolean(),
  narrative_read_only: z.boolean(),
  promotion_allowed: z.boolean(),
  output_hash: z.string(),
  gates: MatrixDecisionReadinessSchema.shape.gates,
  notes: z.array(z.string()),
});

export const ReleaseEvidenceBundleSchema = z.object({
  bundle_version: z.string(),
  bundle_id: z.string(),
  symbol: z.string(),
  target_mode: z.literal("REPLAY"),
  generated_at: z.string(),
  approval: ReleaseApprovalSchema.nullable(),
  checklist: ReleaseChecklistSchema,
  benchmark_report: BehaviorBenchmarkReportSchema,
  benchmark_drilldown: BenchmarkDrilldownSchema,
  evidence_index: z.record(z.string()),
  gate_summary: z.record(z.unknown()),
  final_blockers: z.array(z.string()),
  bundle_hash: z.string(),
  immutable: z.boolean(),
  live_trading_blocked: z.boolean(),
  notes: z.array(z.string()),
});

export const ReleaseEvidenceArtifactSchema = z.object({
  artifact_version: z.string(),
  artifact_id: z.string(),
  symbol: z.string(),
  target_mode: z.literal("REPLAY"),
  created_at: z.string(),
  requested_by: z.string(),
  reason: z.string(),
  artifact_format: z.literal("json_manifest"),
  bundle_id: z.string(),
  bundle_hash: z.string(),
  artifact_dir: z.string(),
  bundle_file_path: z.string(),
  bundle_sha256: z.string(),
  bundle_size_bytes: z.number(),
  manifest_file_path: z.string(),
  manifest_sha256: z.string(),
  manifest_size_bytes: z.number(),
  retention_days: z.number(),
  immutable: z.boolean(),
  live_trading_blocked: z.boolean(),
  contains_broker_credentials: z.boolean(),
  contains_live_orders: z.boolean(),
});

export const ReleaseEvidenceArtifactVerificationSchema = z.object({
  verification_version: z.string(),
  artifact_id: z.string(),
  verified_at: z.string(),
  bundle_file_exists: z.boolean(),
  manifest_file_exists: z.boolean(),
  bundle_sha256_matches: z.boolean(),
  manifest_sha256_matches: z.boolean(),
  bundle_json_parseable: z.boolean(),
  verified: z.boolean(),
  issues: z.array(z.string()),
  live_trading_blocked: z.boolean(),
});
